# Generated by Django 4.0 on 2024-01-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_view_name', 'Can view name'), ('can_change_description', 'Can change description')], 'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
    ]
